databases:
  - name: backendCore

services:
  - type: web
    name: backendCore
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: backendCore
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false